{
 "title": "GigaSpaces Infrastructure",
 "description": "Infrastructure",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"up time\" FROM \"jvm_uptime\" WHERE $timeFilter  and host != '' GROUP BY time($__interval), \"pid\", \"host\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"up time\" FROM \"jvm_uptime\" WHERE $timeFilter and host != '' GROUP BY time($__interval), \"pid\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    }
   ]
  },
  {
   "title": "GSCs CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    }
   ]
  },
  {
   "title": "GSCs memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    }
   ]
  },
  {
   "title": "Managers",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"up time\" FROM \"jvm_uptime\" WHERE $timeFilter  and host != '' GROUP BY time($__interval), \"pid\", \"host\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "lus_zk_rest" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"up time\" FROM \"jvm_uptime\" WHERE $timeFilter and host != '' GROUP BY time($__interval), \"pid\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "lus_zk_rest" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "lus_zk_rest" }
     ]
    }
   ]
  },
  {
   "title": "Managers memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "lus_zk_rest" }
     ]
    }
   ]
  },
  {
   "title": "Managers cpu",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "lus_zk_rest" }
     ]
    }
   ]
  }
 ]
}