{
 "title": "GigaSpaces Main dashboard",
 "tags": [ "Main" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-bytes",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"jvm_memory_heap_used-bytes\" WHERE  pu_name != '' AND $timeFilter GROUP BY  pu_instance_id) where val != 0 GROUP BY  pu_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "!=", "value": "data-feeder-spaceB" }
     ]
    }
   ]
  },
  {
   "title": "Object type count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_space_name : $tag_data_type_short_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "data_type_short_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_data_data-types",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"space_data_data-types\"  WHERE (\"space_active\" = 'true' AND \"data_type_name\" != 'java.lang.Object' AND $timeFilter )  GROUP BY data_type_name, pu_instance_id) where val != 0 GROUP BY data_type_short_name, space_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "data_type_name", "operator": "!=", "value": "java.lang.Object" },
      { "condition": "AND", "key": "data_type_short_name", "operator": "!=", "value": "Value" }
     ]
    }
   ]
  },
  {
   "title": "Spaces",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "space_data_data-types",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "process_cpu_used-percent",
     "query": "SELECT last(\"value\") FROM \"process_cpu_used-percent\" WHERE pu_name != '' and $timeFilter GROUP BY time($__interval), \"pu_name\" fill(null) LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}